# **Classification Model Selection**

Name: Seanrei Ethan M. Valdeabella

January 27, 2024

In [57]:
#@title Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
#@title Importing the Dataset

dataset_name = "Data.csv" #@param {type:"string"}
dataset = pd.read_csv(dataset_name)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [59]:
#@title Splitting the Dataset into the Training Set and Test Set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [60]:
#@title Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **1. Logistic Regression**

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[103   4]
 [  5  59]]

Accuracy Score: 
0.9473684210526315


# **2. K-Nearest Neighbors**

In [62]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski")
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[103   4]
 [  5  59]]

Accuracy Score: 
0.9473684210526315


# **3. Support Vector Machines**

In [63]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = SVC(kernel="linear", random_state=0)
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[102   5]
 [  5  59]]

Accuracy Score: 
0.9415204678362573


# **4. Kernel SVM**

In [64]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = SVC(kernel="rbf", random_state=0)
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[102   5]
 [  3  61]]

Accuracy Score: 
0.9532163742690059


# **5. Naive Bayes**

In [65]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[99  8]
 [ 2 62]]

Accuracy Score: 
0.9415204678362573


# **6. Decision Tree Classification**

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = DecisionTreeClassifier(criterion="entropy", random_state=0)
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[103   4]
 [  3  61]]

Accuracy Score: 
0.9590643274853801


# **7. Random Forest Classification**

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Training
classifier = RandomForestClassifier(n_estimators=100, criterion="gini", random_state=0)
classifier.fit(X_train, y_train)

# Predicting
y_pred = classifier.predict(X_test)

# Model Evaluation
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(f"Confusion Matrix: \n{cm}\n")
print(f"Accuracy Score: \n{accuracy}")

Confusion Matrix: 
[[103   4]
 [  4  60]]

Accuracy Score: 
0.9532163742690059
